service: southwestruby
image: lewispb/southwestruby

servers:
  web:
    hosts:
      - southwestruby.com
    labels:
      traefik.http.routers.southwestruby.rule: Host(`southwestruby.com`)
      traefik.http.routers.southwestruby.middlewares: addwww
      traefik.http.routers.southwestruby_secure.entrypoints: websecure
      traefik.http.routers.southwestruby_secure.rule: Host(`southwestruby.com`)
      traefik.http.routers.southwestruby_secure.tls: true
      traefik.http.routers.southwestruby_secure.tls.certresolver: letsencrypt
      traefik.http.routers.southwestruby_secure.middlewares: addwww

      traefik.http.routers.wwwsouthwestruby.rule: Host(`www.southwestruby.com`)
      traefik.http.routers.wwwsouthwestruby.middlewares: addwww
      traefik.http.routers.wwwsouthwestruby_secure.entrypoints: websecure
      traefik.http.routers.wwwsouthwestruby_secure.rule: Host(`www.southwestruby.com`)
      traefik.http.routers.wwwsouthwestruby_secure.tls: true
      traefik.http.routers.wwwsouthwestruby_secure.tls.certresolver: letsencrypt

      traefik.http.middlewares.addwww.redirectregex.regex: ^(?:http|https)://(?:www\.)?(.*)
      traefik.http.middlewares.addwww.redirectregex.replacement: "https://www.$1"

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    certificatesResolvers.letsencrypt.acme.email: "lewis@lewisbuckley.co.uk"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web

registry:
  username: lewispb
  password:
    - MRSK_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
